// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"
)

type Querier interface {
	AddProfile(ctx context.Context, profileName string) (Profile, error)
	GetAllProfiles(ctx context.Context) ([]Profile, error)
}

var _ Querier = (*Queries)(nil)
