// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package database

import (
	"context"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (profile_id, note, start)
VALUES (
	?,
	?,
	?
	)
RETURNING id, profile_id, created_at, updated_at, note, start, "end"
`

type CreateSessionParams struct {
	ProfileID int64       `json:"profile_id"`
	Note      interface{} `json:"note"`
	Start     string      `json:"start"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.ProfileID, arg.Note, arg.Start)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Note,
		&i.Start,
		&i.End,
	)
	return i, err
}
