-- +goose Up
CREATE TABLE IF NOT EXISTS sessions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    profile_id INTEGER NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    note TEXT NOT NULL DEFAULT 'EMPTY',
    start TEXT NOT NULL,
    end TEXT NOT NULL DEFAULT 'EMPTY',
    FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE
);


-- +goose Down
DROP TABLE sessions;
